### PR TITLE
focus aggregate on consistency boundary

### PR DESCRIPTION
**Pull request by mathiasverraes**

### CODE REVIEW

**Comment by sapiens** [comment]
I propose this:
`**Aggregate**: a consistent group of related objects (often represented as a graph), representing a domain concept
`

**Comment by mathiasverraes** [comment]
The thing is, you can have an aggregate that has no objects at all. Eg using event sourcing or actor model.

**Comment by sapiens** [comment]
Can you elaborate on this? I mean it's pretty common to have an 'aggregate' consisting in one entity only, but no objects at all?! With ES, you still have at least one entity, as ES is just an implementation detail.

**Comment by mathiasverraes** [comment]
> With ES, you still have at least one entity

Not necessarily. You have a stream of events and business rules that are enforced in immediately consistent fashion. An aggregate root object is an implementation detail. You can group those events by the entities that result from them, but I feel that's limiting. It's better to group them according to the business process that the events & rules represent. It's a fundamental shift from thinking in structures to thinking in processes. That's perfectly possible with traditional DDD, but ES is a great catalyst. Therefore, I don't consider ES an implementation detail.

**Comment by sapiens** [comment]
I understand what you're saying, you're taking a functional approach, in my opinion an implementation detail. I don't view a stream of events and process related business rules as defining an aggregate though. Basically, the aggregate root would be a state computed from the stream.  And  the functional approach can turn very quickly into an anemic domain (to nitpick, an event is still a data structure implemented as an object by most languages).

I know there are multiple correct ways to look at a problem and in the end it depends on what the modeller feels more comfortable with.

**Comment by mathiasverraes** [comment]
Event Sourcing is neither OOP or FP, and can be implemented in both. Eric has stated at many occasions that OOP just happened to be the dominant paradigm when he wrote the blue book. If you take his definition of aggregates, and remove the references to OOP, what you are left with is that an aggregate is a transaction boundary around invariants. So the question when defining aggregates, imho, is not "which objects belong together", but "which invariants need to be met at all times". An invariant can be seen as a decision point that uses existing state to make a decision about a next state. Considering that state is but a by-product of behavior, we can also say that an invariant is a decision point that uses previous events to make a decision about a next event. So to make the boundary around the business rules, we also need that boundary around the events that the business rules need to make their decision. This boundary might happily coincide with a "thing" in the domain, but often, more "things" might be involved. The model where the boundary coincides with the thing, doesn't work anymore. This is exactly why aggregates are considered hard. The alternative is to forget about the things (on the write side) and look for the processes instead, which has been working quite well for me. I guess I need to blog about it :-) 

> I know there are multiple correct ways 

All models are wrong, but some are more useful ;-)

> And the functional approach can turn very quickly into an anemic domain 

wat_grande

**Comment by sapiens** [comment]
Clearly we have different views over the matter, you're using a functional mindset, while I'm using an OOP mindset. The aggregate 'definition' shouldn't depend on one implementation detail or another.

So, what do you say about `all data and consistency rules defining a domain concept valid for a given use case` ? A bit too  unfriendly for my taste, but it doesn't imply a specific implementation

**Comment by mathiasverraes** [comment]
I agree it's not helpful to newcomers. How about splitting it up? A
definition for event sourced and oop aggregates?

—
Mathias Verraes
Software Consultant
Value Object Comm.V http://value-object.com
Blog http://verraes.net/ - Email mathias@verraes.net -  Twitter
http://twitter.com/mathiasverraes - LinkedIn
https://www.linkedin.com/in/mathiasverraes

**Comment by sapiens** [comment]
Yeah, that's the best option.

**Comment by kirkbushell** [comment]
@mathiasverraes would really love to see that blog post about this :) I'm struggling with designing good aggregates.

**Pull request merged**
